<Project>
    <PropertyGroup>
        <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Prefer32Bit>false</Prefer32Bit>
        <OutputType>Library</OutputType>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>embedded</DebugType>
        <Optimize>false</Optimize>
        <OutputPath>$(MSBuildProjectDirectory)\out\Assemblies</OutputPath>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DebugType>embedded</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>$(MSBuildProjectDirectory)\out\Assemblies</OutputPath>
        <DefineConstants>TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>

    <PropertyGroup>
      <RimworldVersion>1.6</RimworldVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0" />
        <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" />
        <PackageReference Include="Lib.Harmony" Version="2.3.6" ExcludeAssets="runtime" />
    </ItemGroup>

    <ItemGroup>
        <Publicize Include="Assembly-CSharp"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="mod\**" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <ItemGroup>
            <MyMod Include="$(MSBuildProjectDirectory)\mod\**\*.*" />
        </ItemGroup>

        <RemoveDir Directories="$(MSBuildProjectDirectory)\out\About" />
        <RemoveDir Directories="$(MSBuildProjectDirectory)\out\Defs" />
        <RemoveDir Directories="$(MSBuildProjectDirectory)\out\Patches" />
        <RemoveDir Directories="$(MSBuildProjectDirectory)\out\Languages" />
        <Copy SourceFiles="@(MyMod)" DestinationFolder="$(MSBuildProjectDirectory)\out\%(RecursiveDir)" />
    </Target>

    <Target Name="CopyToRimworldDebug">
        <ItemGroup>
            <BuiltMod Include="$(MSBuildProjectDirectory)\out\**\*.*" />
        </ItemGroup>

        <RemoveDir Directories="G:\RimWorld_Debug\Mods\$(MSBuildProjectName)" />
        <Copy SourceFiles="@(BuiltMod)" DestinationFolder="G:\RimWorld_Debug\Mods\$(MSBuildProjectName)\%(RecursiveDir)" />
    </Target>

    <Target Name="CopyToRimworld">
        <ItemGroup>
            <BuiltMod Include="$(MSBuildProjectDirectory)\out\**\*.*" />
        </ItemGroup>

        <RemoveDir Directories="F:\SteamLibrary\steamapps\common\RimWorld\Mods\$(MSBuildProjectName)" />
        <Copy SourceFiles="@(BuiltMod)" DestinationFolder="F:\SteamLibrary\steamapps\common\RimWorld\Mods\$(MSBuildProjectName)\%(RecursiveDir)" />
    </Target>
</Project>