<?xml version="1.0" encoding="utf-8"?>


<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
        <OutputType>Library</OutputType>
        <AppDesignerFolder>Properties</AppDesignerFolder>
        <AssemblyName>BioFuelFertilizer</AssemblyName>
        <RootNamespace>Ordo.BioFuelFertilizer</RootNamespace>
        <FileAlignment>512</FileAlignment>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="VFEF">
            <HintPath>F:\SteamLibrary\steamapps\workshop\content\294100\1957158779\$(RimworldVersion)\Assemblies\VFEF.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <Reference Include="VFEF">
            <HintPath>F:\SteamLibrary\steamapps\workshop\content\294100\3155781848\$(RimworldVersion)\Assemblies\VanillaRecyclingExpanded.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <Reference Include="BadHygiene">
            <HintPath>F:\SteamLibrary\steamapps\workshop\content\294100\836308268\$(RimworldVersion)\Assemblies\BadHygiene.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

</Project>